# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

# See docs at https://www.packer.io/docs/install/index.html
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_LABR_IMAGE}:${_LABR_VERSION}',
           '-t', 'gcr.io/$PROJECT_ID/${_LABR_IMAGE}',
           '.']
timeout: 900s
substitutions:           
  _LABR_VERSION: 0.0.1
  _LABR_IMAGE: labr 

images:
  - 'gcr.io/$PROJECT_ID/${_LABR_IMAGE}:latest'
  - 'gcr.io/$PROJECT_ID/${_LABR_IMAGE}:${_LABR_VERSION}'
tags: ['lab-developer']
